//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "email_job_attachments")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub email_job_id: i64,
    pub filename: String,
    pub content_type: String,
    pub content: Vec<u8>,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::email_jobs::Entity",
        from = "Column::EmailJobId",
        to = "super::email_jobs::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    EmailJobs,
}

impl Related<super::email_jobs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EmailJobs.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
