//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "mega_view_filter")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub filter_id: String,
    pub canonical_spec: String,
    pub algo_version: i16,
    pub object_format: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub src_paths: Json,
    pub push_enabled: bool,
    pub projected_seq: i64,
    pub ready_seq: Option<i64>,
    pub warming_since: Option<DateTime>,
    pub last_access_at: Option<DateTime>,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
