//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use super::sea_orm_active_enums::{
    PushQueueFailureEnum, PushQueueKindEnum, PushQueuePendingEnum, PushQueueStatusEnum,
};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "push_queue")]
pub struct Model {
    /// Authoritative global order of queue operations, shared by the `push`,
    /// `merge` and `attach` rows (ADR-TP-06). Database-assigned `bigserial`,
    /// unlike the application-assigned ids used elsewhere in `callisto`.
    #[sea_orm(primary_key)]
    pub id: i64,
    pub kind: PushQueueKindEnum,
    #[sea_orm(column_type = "Text")]
    pub operation_id: String,
    #[sea_orm(column_type = "Text")]
    pub path: String,
    #[sea_orm(column_type = "Text")]
    pub old_id: String,
    #[sea_orm(column_type = "Text")]
    pub new_id: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub payload: Json,
    #[sea_orm(column_type = "Text", nullable)]
    pub landed_commit_id: Option<String>,
    pub status: PushQueueStatusEnum,
    #[sea_orm(column_type = "Text", nullable)]
    pub requester: Option<String>,
    pub failure_type: Option<PushQueueFailureEnum>,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_message: Option<String>,
    pub heartbeat_at: DateTimeWithTimeZone,
    pub superseded_by: Option<i64>,
    /// Root identity baseline written inside the B2.5 claim transaction; NULL
    /// is the sentinel for "the ref row was missing".
    #[sea_orm(column_type = "Text", nullable)]
    pub expected_commit_hash: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub expected_tree_hash: Option<String>,
    pub pending_action: Option<PushQueuePendingEnum>,
    pub enqueued_at: DateTimeWithTimeZone,
    pub started_at: Option<DateTimeWithTimeZone>,
    pub finished_at: Option<DateTimeWithTimeZone>,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

#[cfg(test)]
mod tests {
    use sea_orm::{ConnectionTrait, DatabaseConnection, DbBackend, Statement, TransactionTrait};
    use sea_orm_migration::{SchemaManager, prelude::MigrationTrait};

    use crate::jupiter::{migration::apply_migrations, tests::test_db_connection};

    async fn migrated_db() -> (tempfile::TempDir, DatabaseConnection) {
        let temp_dir = tempfile::TempDir::new().expect("temp dir");
        let db = test_db_connection(temp_dir.path()).await;
        apply_migrations(&db, false)
            .await
            .expect("migrations should apply");
        (temp_dir, db)
    }

    /// The test schemas are isolated through `search_path` (see
    /// `jupiter::tests`) while the catalog spans every schema, so every
    /// catalog query here must be scoped to `current_schema()`.
    async fn scalar(db: &DatabaseConnection, sql: &str) -> Option<String> {
        let row = db
            .query_one_raw(Statement::from_string(DbBackend::Postgres, sql.to_owned()))
            .await
            .expect("catalog query")?;
        row.try_get::<Option<String>>("", "value")
            .expect("value column")
    }

    async fn enum_labels(db: &DatabaseConnection, type_name: &str) -> Option<Vec<String>> {
        let labels = scalar(
            db,
            &format!(
                "SELECT string_agg(e.enumlabel, ',' ORDER BY e.enumsortorder) AS value \
                 FROM pg_type t \
                 JOIN pg_namespace n ON n.oid = t.typnamespace \
                 JOIN pg_enum e ON e.enumtypid = t.oid \
                 WHERE n.nspname = current_schema() AND t.typname = '{type_name}'"
            ),
        )
        .await?;
        Some(labels.split(',').map(str::to_owned).collect())
    }

    /// `(data_type, is_nullable)` of a column in the current schema.
    async fn column(db: &DatabaseConnection, table: &str, name: &str) -> Option<(String, String)> {
        let row = db
            .query_one_raw(Statement::from_string(
                DbBackend::Postgres,
                format!(
                    "SELECT data_type, is_nullable FROM information_schema.columns \
                     WHERE table_schema = current_schema() AND table_name = '{table}' \
                     AND column_name = '{name}'"
                ),
            ))
            .await
            .expect("catalog query")?;
        Some((
            row.try_get("", "data_type").expect("data_type"),
            row.try_get("", "is_nullable").expect("is_nullable"),
        ))
    }

    async fn insert_row(
        db: &DatabaseConnection,
        kind: &str,
        path: &str,
        operation_id: &str,
        status: &str,
    ) -> Result<(), String> {
        db.execute_unprepared(&format!(
            "INSERT INTO push_queue \
             (kind, operation_id, path, old_id, new_id, payload, status, \
              heartbeat_at, enqueued_at, updated_at) \
             VALUES ('{kind}', '{operation_id}', '{path}', 'old', 'new', '{{}}'::jsonb, \
                     '{status}', now(), now(), now())"
        ))
        .await
        .map(|_| ())
        .map_err(|e| e.to_string())
    }

    #[tokio::test]
    async fn tp01_migration_creates_the_tables_and_the_four_enum_types() {
        let (_temp_dir, db) = migrated_db().await;

        for table in ["push_queue", "queue_control"] {
            let name = scalar(
                &db,
                &format!(
                    "SELECT table_name AS value FROM information_schema.tables \
                     WHERE table_schema = current_schema() AND table_name = '{table}'"
                ),
            )
            .await;
            assert_eq!(name.as_deref(), Some(table), "table '{table}' must exist");
        }

        assert_eq!(
            enum_labels(&db, "push_queue_status_enum").await,
            Some(vec![
                "Queued".to_owned(),
                "Running".to_owned(),
                "Done".to_owned(),
                "Failed".to_owned(),
                "Cancelled".to_owned(),
            ])
        );
        assert_eq!(
            enum_labels(&db, "push_queue_kind_enum").await,
            Some(vec![
                "push".to_owned(),
                "merge".to_owned(),
                "attach".to_owned()
            ])
        );
        assert_eq!(
            enum_labels(&db, "push_queue_failure_enum").await,
            Some(vec![
                "PushFailure".to_owned(),
                "MergeFailure".to_owned(),
                "AttachFailure".to_owned(),
                "Conflict".to_owned(),
                "QueueBypassDetected".to_owned(),
                "WaitTimeout".to_owned(),
                "ClaimLost".to_owned(),
                "SystemError".to_owned(),
            ])
        );
        assert_eq!(
            enum_labels(&db, "push_queue_pending_enum").await,
            Some(vec!["requeue_conflict".to_owned()]),
            "pending_action carries only the conflict requeue intent"
        );
    }

    #[tokio::test]
    async fn tp01_push_queue_columns_match_the_declared_schema() {
        let (_temp_dir, db) = migrated_db().await;

        for (name, data_type, is_nullable) in [
            ("id", "bigint", "NO"),
            ("kind", "USER-DEFINED", "NO"),
            ("operation_id", "text", "NO"),
            ("path", "text", "NO"),
            ("payload", "jsonb", "NO"),
            ("landed_commit_id", "text", "YES"),
            ("status", "USER-DEFINED", "NO"),
            ("requester", "text", "YES"),
            ("failure_type", "USER-DEFINED", "YES"),
            ("heartbeat_at", "timestamp with time zone", "NO"),
            ("superseded_by", "bigint", "YES"),
            ("expected_commit_hash", "text", "YES"),
            ("expected_tree_hash", "text", "YES"),
            ("pending_action", "USER-DEFINED", "YES"),
            ("enqueued_at", "timestamp with time zone", "NO"),
            ("started_at", "timestamp with time zone", "YES"),
            ("finished_at", "timestamp with time zone", "YES"),
            ("updated_at", "timestamp with time zone", "NO"),
        ] {
            assert_eq!(
                column(&db, "push_queue", name).await,
                Some((data_type.to_owned(), is_nullable.to_owned())),
                "push_queue.{name}"
            );
        }

        // `id` is database-assigned (ADR-TP-06 queue order), not an
        // application-assigned key like the rest of `callisto`. `sea_query`
        // renders `auto_increment` as an identity column rather than the
        // `bigserial` spelling of 1.4; both take their values from a sequence.
        let assigned_by_db = scalar(
            &db,
            "SELECT (is_identity = 'YES' OR column_default LIKE 'nextval(%')::text AS value \
             FROM information_schema.columns \
             WHERE table_schema = current_schema() AND table_name = 'push_queue' \
             AND column_name = 'id'",
        )
        .await;
        assert_eq!(
            assigned_by_db.as_deref(),
            Some("true"),
            "push_queue.id must be database-assigned"
        );

        for col in ["enqueued_at", "updated_at"] {
            let default = scalar(
                &db,
                &format!(
                    "SELECT column_default AS value FROM information_schema.columns \
                     WHERE table_schema = current_schema() AND table_name = 'push_queue' \
                     AND column_name = '{col}'"
                ),
            )
            .await;
            assert!(
                default
                    .as_deref()
                    .is_some_and(|d| d.contains("now") || d.contains("CURRENT_TIMESTAMP")),
                "push_queue.{col} must default to now() so B1 INSERT (1.5) need not supply it: {default:?}"
            );
        }
    }

    /// Exact column list of the authoritative B1 INSERT in trunk-push.md 1.5 —
    /// must succeed without naming `enqueued_at` / `updated_at`.
    #[tokio::test]
    async fn tp01_b1_insert_column_list_relies_on_timestamp_defaults() {
        let (_temp_dir, db) = migrated_db().await;
        db.execute_unprepared(
            "INSERT INTO push_queue \
             (kind, operation_id, path, old_id, new_id, requester, payload, status, heartbeat_at) \
             VALUES ('push', 'op-b1', '/b1', 'old', 'new', NULL, '{}'::jsonb, 'Queued', now())",
        )
        .await
        .expect("B1 column list must insert without enqueued_at/updated_at");

        let row = db
            .query_one_raw(Statement::from_string(
                DbBackend::Postgres,
                "SELECT enqueued_at IS NOT NULL AS e, updated_at IS NOT NULL AS u \
                 FROM push_queue WHERE operation_id = 'op-b1'"
                    .to_owned(),
            ))
            .await
            .expect("query")
            .expect("row");
        let enqueued: bool = row.try_get("", "e").expect("e");
        let updated: bool = row.try_get("", "u").expect("u");
        assert!(
            enqueued && updated,
            "defaults must populate both timestamps"
        );
    }

    #[tokio::test]
    async fn tp01_active_push_path_admits_one_in_flight_push_per_path() {
        let (_temp_dir, db) = migrated_db().await;

        insert_row(&db, "push", "/project/a", "op-1", "Queued")
            .await
            .expect("first queued push");

        // Same path, different operation: the index keys on `path` alone, so
        // the second push is rejected (ADR-TP-10).
        let err = insert_row(&db, "push", "/project/a", "op-2", "Queued")
            .await
            .expect_err("a second in-flight push on the same path is rejected");
        assert!(
            err.contains("push_queue_active_push_path"),
            "expected the partial unique index to reject the insert: {err}"
        );

        // `Running` is in flight too.
        let err = insert_row(&db, "push", "/project/a", "op-3", "Running")
            .await
            .expect_err("a Running push on the same path is rejected");
        assert!(err.contains("push_queue_active_push_path"), "{err}");

        // Terminal rows are outside the predicate and block nothing.
        insert_row(&db, "push", "/project/b", "op-4", "Failed")
            .await
            .expect("failed push");
        insert_row(&db, "push", "/project/b", "op-5", "Cancelled")
            .await
            .expect("cancelled push on a path with a failed one");
        insert_row(&db, "push", "/project/b", "op-6", "Queued")
            .await
            .expect("terminal rows must not block a new push");

        // The index is scoped to `kind = 'push'`; merge and attach queue
        // freely behind an in-flight push.
        insert_row(&db, "merge", "/project/a", "op-7", "Queued")
            .await
            .expect("merge is exempt");
        insert_row(&db, "attach", "/project/a", "op-8", "Queued")
            .await
            .expect("attach is exempt");
    }

    #[tokio::test]
    async fn tp01_operation_states_is_unique_across_queued_running_and_done() {
        let (_temp_dir, db) = migrated_db().await;

        // `kind = 'merge'` keeps `push_queue_active_push_path` out of the way,
        // so a rejection here can only come from the operation index.
        insert_row(&db, "merge", "/project/c", "op-1", "Queued")
            .await
            .expect("first row");

        for status in ["Queued", "Running", "Done"] {
            let err = insert_row(&db, "merge", "/project/c", "op-1", status)
                .await
                .expect_err("a duplicate operation in a non-terminal state is rejected");
            assert!(
                err.contains("push_queue_operation_states"),
                "expected the operation index to reject '{status}': {err}"
            );
        }

        insert_row(&db, "merge", "/project/c", "op-2", "Queued")
            .await
            .expect("a different operation_id is a different operation");
        insert_row(&db, "merge", "/project/d", "op-1", "Queued")
            .await
            .expect("a different path is a different operation");
        insert_row(&db, "attach", "/project/c", "op-1", "Queued")
            .await
            .expect("a different kind is a different operation");

        // Terminal rows leave the three states, which is what makes the
        // conflict requeue of B4 possible.
        insert_row(&db, "merge", "/project/e", "op-1", "Failed")
            .await
            .expect("failed row");
        insert_row(&db, "merge", "/project/e", "op-1", "Cancelled")
            .await
            .expect("cancelled row alongside the failed one");
        insert_row(&db, "merge", "/project/e", "op-1", "Queued")
            .await
            .expect("terminal rows must not block a requeue of the same operation");
    }

    #[tokio::test]
    async fn tp01_queue_control_row_can_be_locked_for_update() {
        let (_temp_dir, db) = migrated_db().await;

        let txn = db.begin().await.expect("begin");
        let row = txn
            .query_one_raw(Statement::from_string(
                DbBackend::Postgres,
                "SELECT paused, max_depth FROM queue_control WHERE id = 1 FOR UPDATE".to_owned(),
            ))
            .await
            .expect("FOR UPDATE on queue_control")
            .expect("B1 must find a row to lock");
        let paused: bool = row.try_get("", "paused").expect("paused");
        let max_depth: i32 = row.try_get("", "max_depth").expect("max_depth");
        assert!(!paused);
        assert_eq!(max_depth, 64);
        txn.commit().await.expect("commit");
    }

    /// `down` is empty, so the only recovery path is a replay of `up` — the
    /// case where the migration tracking table was lost but the schema was
    /// not. Every statement in `up` therefore has to tolerate its own output:
    /// the enums through the `duplicate_object` guard, the tables through
    /// `if_not_exists`, the indexes through `IF NOT EXISTS` and the seed
    /// through `ON CONFLICT DO NOTHING`.
    #[tokio::test]
    async fn tp01_migration_up_can_be_replayed_over_an_existing_schema() {
        let (_temp_dir, db) = migrated_db().await;

        insert_row(&db, "push", "/project/replay", "op-1", "Queued")
            .await
            .expect("a row the replay must not destroy");

        crate::jupiter::migration::m20260905_000100_add_push_queue::Migration
            .up(&SchemaManager::new(&db))
            .await
            .expect("re-running up over an existing schema must succeed");

        assert_eq!(
            enum_labels(&db, "push_queue_pending_enum").await,
            Some(vec!["requeue_conflict".to_owned()]),
            "the guarded CREATE TYPE must leave the existing labels alone"
        );

        let rows = scalar(&db, "SELECT count(*)::text AS value FROM push_queue").await;
        assert_eq!(rows.as_deref(), Some("1"), "the table was not recreated");

        let control_rows = scalar(&db, "SELECT count(*)::text AS value FROM queue_control").await;
        assert_eq!(
            control_rows.as_deref(),
            Some("1"),
            "the replayed seed must not add a second control row"
        );

        // The index still rejects a second in-flight push, so the replay did
        // not drop it either.
        insert_row(&db, "push", "/project/replay", "op-2", "Queued")
            .await
            .expect_err("push_queue_active_push_path must survive the replay");
    }
}
