//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "queue_control")]
pub struct Model {
    /// Single-row table: the schema pins `id` to 1 with a check constraint, so
    /// B1 always has exactly one row to take `FOR UPDATE` on.
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    /// Maintenance pause: drain-only — new admissions are refused, queued
    /// items still execute.
    pub paused: bool,
    /// Fail-closed hard stop, reserved for `QueueBypassDetected`.
    pub hard_stopped: bool,
    /// `push_policy` of the previous run, the input to the startup shape-change
    /// check.
    #[sea_orm(column_type = "Text")]
    pub last_policy: String,
    pub max_depth: i32,
    /// Monotonic authz snapshot publish watermark (TP-22). CAS:
    /// `UPDATE ... SET published_version = $v WHERE published_version < $v`.
    pub published_version: i64,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

#[cfg(test)]
mod tests {
    use sea_orm::{
        ConnectionTrait, DatabaseConnection, DbBackend, EntityTrait, PaginatorTrait, Statement,
    };

    use crate::jupiter::{
        migration::{
            apply_migrations, ensure_queue_control_seed,
            m20260905_000100_add_push_queue::SEED_QUEUE_CONTROL,
        },
        tests::test_db_connection,
    };

    async fn row_count(db: &DatabaseConnection) -> u64 {
        super::Entity::find()
            .count(db)
            .await
            .expect("count queue_control rows")
    }

    #[tokio::test]
    async fn tp01_migration_seeds_exactly_one_control_row() {
        let temp_dir = tempfile::TempDir::new().expect("temp dir");
        let db = test_db_connection(temp_dir.path()).await;
        apply_migrations(&db, false)
            .await
            .expect("migrations should apply");

        assert_eq!(row_count(&db).await, 1);

        let row = super::Entity::find_by_id(1)
            .one(&db)
            .await
            .expect("query the control row")
            .expect("the migration seeds id = 1");
        assert!(!row.paused);
        assert!(!row.hard_stopped);
        assert_eq!(row.last_policy, "review");
        assert_eq!(row.max_depth, 64);
        assert_eq!(row.published_version, 0);
    }

    #[tokio::test]
    async fn tp01_reseeding_is_idempotent_and_the_row_stays_unique() {
        let temp_dir = tempfile::TempDir::new().expect("temp dir");
        let db = test_db_connection(temp_dir.path()).await;
        apply_migrations(&db, false)
            .await
            .expect("migrations should apply");

        // Re-running the seed is how startup re-asserts the row exists; the
        // `ON CONFLICT DO NOTHING` must make that a no-op rather than an error.
        for _ in 0..2 {
            db.execute_unprepared(SEED_QUEUE_CONTROL)
                .await
                .expect("re-seeding must not error");
        }
        assert_eq!(row_count(&db).await, 1);

        // A second row is rejected by the `id = 1` check constraint, so
        // "exactly one" does not rest on the seed being the only writer.
        let err = db
            .execute_raw(Statement::from_string(
                DbBackend::Postgres,
                "INSERT INTO queue_control (id, paused, hard_stopped, last_policy, max_depth, \
                 updated_at) VALUES (2, false, false, 'review', 64, now())"
                    .to_owned(),
            ))
            .await
            .expect_err("a second control row must be rejected");
        assert!(
            err.to_string().contains("queue_control_single_row"),
            "expected the check constraint to reject the insert: {err}"
        );
        assert_eq!(row_count(&db).await, 1);
    }

    /// The startup half of "迁移/启动播种": a database that lost the row — an
    /// older dump, a manual delete — must get it back on the next boot rather
    /// than run with a `FOR UPDATE` that locks nothing.
    #[tokio::test]
    async fn tp01_startup_seed_restores_a_missing_control_row() {
        let temp_dir = tempfile::TempDir::new().expect("temp dir");
        let db = test_db_connection(temp_dir.path()).await;
        apply_migrations(&db, false)
            .await
            .expect("migrations should apply");

        db.execute_unprepared("DELETE FROM queue_control")
            .await
            .expect("delete the control row");
        assert_eq!(row_count(&db).await, 0);

        ensure_queue_control_seed(&db)
            .await
            .expect("startup seed must restore the row");

        let row = super::Entity::find_by_id(1)
            .one(&db)
            .await
            .expect("query the control row")
            .expect("the startup seed re-creates id = 1");
        assert!(!row.paused);
        assert!(!row.hard_stopped);
        assert_eq!(row.last_policy, "review");
        assert_eq!(row.max_depth, 64);
        assert_eq!(row_count(&db).await, 1);
    }

    /// `ON CONFLICT DO NOTHING`, not an upsert: the startup seed runs on every
    /// boot, so overwriting would silently undo an operator's pause, hard stop
    /// or depth change, and would reset the `last_policy` that the 4.1
    /// shape-change check reads.
    #[tokio::test]
    async fn tp01_startup_seed_preserves_operator_set_values() {
        let temp_dir = tempfile::TempDir::new().expect("temp dir");
        let db = test_db_connection(temp_dir.path()).await;
        apply_migrations(&db, false)
            .await
            .expect("migrations should apply");

        db.execute_unprepared(
            "UPDATE queue_control SET paused = true, hard_stopped = true, \
             last_policy = 'trunk', max_depth = 7, updated_at = now() WHERE id = 1",
        )
        .await
        .expect("operator changes the control row");

        ensure_queue_control_seed(&db)
            .await
            .expect("re-seeding an existing row must be a no-op");

        let row = super::Entity::find_by_id(1)
            .one(&db)
            .await
            .expect("query the control row")
            .expect("the row is still there");
        assert!(row.paused, "paused must survive the startup seed");
        assert!(row.hard_stopped, "hard_stopped must survive");
        assert_eq!(row.last_policy, "trunk");
        assert_eq!(row.max_depth, 7);
        assert_eq!(row_count(&db).await, 1);
    }
}
