//! TP-22: authz notify outbox + monotonic `published_version` (trunk-push 1.2).
//!
//! `authz_notify_outbox.version` is `push_queue.id` for B3-enqueued rebuilds,
//! or NULL for queue-external dirty marks. `queue_control.published_version`
//! is the CAS watermark for snapshot publish order.
//!
//! Forward-only (`down` is empty).

use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        let conn = manager.get_connection();
        conn.execute_unprepared(
            "ALTER TABLE queue_control \
             ADD COLUMN IF NOT EXISTS published_version bigint NOT NULL DEFAULT 0",
        )
        .await?;
        conn.execute_unprepared(
            "CREATE TABLE IF NOT EXISTS authz_notify_outbox (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                version bigint,
                dirty boolean NOT NULL DEFAULT false,
                created_at timestamptz NOT NULL DEFAULT now(),
                replayed_at timestamptz
            )",
        )
        .await?;
        conn.execute_unprepared(
            "CREATE INDEX IF NOT EXISTS authz_notify_outbox_pending_idx \
             ON authz_notify_outbox (created_at) WHERE replayed_at IS NULL",
        )
        .await
        .map(|_| ())
    }

    async fn down(&self, _manager: &SchemaManager) -> Result<(), DbErr> {
        Ok(())
    }
}
