use std::path::Path;

use anyhow::{Result, anyhow};

pub fn default_config_template(bin_name: &str) -> Result<&'static str> {
    match bin_name {
        "mono" => Ok(include_str!("../../config/config.toml")),
        "monoengine" => Ok(include_str!("../../config/config.toml")),
        "orion-server" => Ok(include_str!("../../config/config.toml")),
        _ => Err(anyhow!("unknown binary `{}`", bin_name)),
    }
}

pub fn config_init_template(base_dir: &Path) -> String {
    let base_dir = base_dir.to_string_lossy();
    format!(
        r#"# monoengine configuration skeleton generated by `monoengine config init`.
# Do not store production passwords in this file. Bootstrap credentials such as
# database, Redis, and object storage secrets should be injected by your
# deployment platform or MEGA_* environment variables.
base_dir = "{base_dir}"

[log]
level = "info"
print_std = true
with_ansi = true

[database]
db_type = "postgres"
# Override with MEGA_DATABASE__DB_URL or a deployment secret. Do not put a
# reusable production password in this file.
db_url = "postgres://localhost:5432/monoengine"
max_connection = 16
min_connection = 4
acquire_timeout = 5
connect_timeout = 5
sqlx_logging = false

[monorepo]
import_dir = "/third-party"
admin = ["admin"]
root_dirs = ["third-party", "project", "doc", "release", "toolchains"]
# Object-ID format for the initial Monorepo graph. Values: sha1 (default), sha256.
# blake3 remains reserved until an explicit repository hash context is wired for
# normal Git services; SHA-256 is bootstrap-only until the same context exists.
# Do not use SHA-256 for a normal Git service; run `service init --yes` only.
object_format = "sha1"
# Push morphology: "review" (default, CL pipeline) or "trunk" (MonoWriteQueue).
# Restart-required. Trunk requires cedar.enforcement="off", no open CLs, and
# an explicit git.push_auth of "token" or "none".
# push_policy = "review"
# Trunk-only first-parent chain bound. Review morphology keeps MAX_CL_CHAIN_COMMITS=250.
# max_push_commits = 250

[monorepo.rename]
similarity_threshold = 50
rename_limit = 1000

[build]
enable_build = false
orion_server = "http://localhost:8004"
orion_preheat_shallow_depth = 0

[pack]
pack_decode_mem_size = "4G"
pack_decode_disk_size = "20%"
pack_decode_cache_path = "{base_dir}/cache/pack_decode"
clean_cache_after_decode = true
channel_message_size = 1000000
save_entry_concurrency = 1

[lfs.ssh]
http_url = "http://localhost:8000"

[lfs.local]
lfs_file_path = "{base_dir}/lfs"

[redis]
# Override with MEGA_REDIS__URL or a deployment secret when Redis requires auth.
url = "redis://127.0.0.1:6379"

[object_storage]
# Only the section matching storage_type is required; omit unused backends.
storage_type = "local"

[object_storage.local]
root_dir = "{base_dir}/objects"

# Uncomment when storage_type = "s3" | "s3compatible":
# [object_storage.s3]
# region = ""
# bucket = ""
# access_key_id = ""
# secret_access_key = ""
# endpoint_url = ""

# Uncomment when storage_type = "gcs":
# [object_storage.gcs]
# bucket = ""

[artifacts_gc]
enable = false
interval_secs = 3600
grace_secs = 86400
batch_limit = 100

# Git protocol / trunk push authentication. Omitted push_auth = OAuth/UserStorage
# (review only). "token" | "none" requires monorepo.push_policy = "trunk".
# [git]
# anonymous_access = true
# push_auth = "token"
# ssh_receive_pack = false
# [[git.push_tokens]]
# name = "team-foo"
# token = "${{file:/run/secrets/team_foo_token}}"
# paths = ["/project/foo"]

"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::{Config, testing::env_lock};

    fn assert_no_predictable_credentials(rendered: &str) {
        for (username, password) in [("mono", "mono"), ("mega", "mega"), ("postgres", "postgres")] {
            let db_url_userinfo = ["postgres://", username, ":", password, "@"].concat();
            assert!(!rendered.contains(&db_url_userinfo));
        }
        assert!(!rendered.contains(&["password", " = "].concat()));
    }

    #[test]
    fn config_init_template_parses_and_avoids_plaintext_credentials() {
        let _lock = env_lock();
        let rendered = config_init_template(Path::new("/tmp/monoengine"));

        let config = Config::load_str(&rendered).expect("init template should parse");
        config.validate().expect("init template should validate");

        assert_no_predictable_credentials(&rendered);
    }

    #[test]
    fn bundled_config_template_parses_and_avoids_plaintext_credentials() {
        let _lock = env_lock();
        let rendered = default_config_template("monoengine").expect("default template");

        let config = Config::load_str(rendered).expect("bundled template should parse");
        config.validate().expect("bundled template should validate");

        assert_no_predictable_credentials(rendered);
    }
}
